# -----------------------------------------------------------------------------
# cleanup_repo.ps1 -- reorganise D:\FFT_ENGINE and remove regenerable clutter
#
#   .\scripts\cleanup_repo.ps1              # DRY RUN -- shows what it would do
#   .\scripts\cleanup_repo.ps1 -Execute     # actually does it
#
# Dry run by default on purpose: deletion is irreversible, and you should read
# the DELETE list once before trusting it. Nothing in that list is a source
# file -- every entry is regenerated by a tool on the next run.
#
# NOTHING here touches: rtl/ tb/ scripts/ constraints/ attic/ ctm_test/
# vivado_ip_kc705/ build_synth.tcl .gitignore, or the three live docs.
# -----------------------------------------------------------------------------
param([switch]$Execute)

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
Set-Location $root

$mode = if ($Execute) { "EXECUTE" } else { "DRY RUN" }
Write-Host ""
Write-Host "=== FFT_ENGINE cleanup -- $mode ===" -ForegroundColor Cyan
Write-Host "    root: $root"
Write-Host ""

function Do-Move($src, $dstDir) {
    if (-not (Test-Path $src)) { return }
    Write-Host "  MOVE   $src  ->  $dstDir/" -ForegroundColor Yellow
    if ($Execute) {
        New-Item -ItemType Directory -Force -Path $dstDir | Out-Null
        Move-Item -Force -Path $src -Destination $dstDir
    }
}

# -----------------------------------------------------------------------------
# PROTECTED -- never deletable, whatever any list below says. Belt and braces
# after the 2 Sep near-miss: the first version of this script passed
# "vivado_ip" to Get-ChildItem -Path. PowerShell resolved it literally, so
# vivado_ip_kc705 survived -- but had it been treated as a prefix, the
# generated xfft_0 core every script depends on would have been destroyed.
# Two directory names differing only by suffix must never be separated by
# luck. Do-DeleteDir now refuses anything on this list, by exact name.
# -----------------------------------------------------------------------------
$Protected = @(
    "rtl", "tb", "scripts", "constraints", "attic", "docs",
    "vivado_ip_kc705",   # the generated xfft_0 IP -- everything depends on it
    "ctm_test"           # the MIG DDR3 IP for the real corner turn
)

# Files, by wildcard. Only ever matches files, never recurses into directories.
function Do-DeleteFile($pattern) {
    $items = Get-ChildItem -Path $pattern -Force -File -ErrorAction SilentlyContinue
    foreach ($i in $items) {
        Write-Host ("  DELETE {0,-34} {1,10:N0} B" -f $i.Name, $i.Length) -ForegroundColor Red
        if ($Execute) { Remove-Item -Force -LiteralPath $i.FullName }
    }
}

# Directories, by EXACT name. -LiteralPath so no wildcard or prefix matching
# is possible, plus a hard refusal on the protected list.
function Do-DeleteDir($name) {
    if ($Protected -contains $name) {
        Write-Host "  REFUSE $name -- on the protected list" -ForegroundColor Magenta
        return
    }
    if (-not (Test-Path -LiteralPath $name -PathType Container)) { return }
    Write-Host "  DELETE $name/  (directory and all contents)" -ForegroundColor Red
    if ($Execute) { Remove-Item -Recurse -Force -LiteralPath $name }
}

# =============================================================================
# 1. ORGANISE -- documentation and figures into docs/
# =============================================================================
# Kept in the root, deliberately: README.md (entry point), ARCHITECTURE_3D.md
# (the live design + verification record), SPEC_FROZEN.md (the contract).
# Everything else below is history worth keeping but not worth tripping over.
Write-Host "--- organising docs ---" -ForegroundColor Green
foreach ($f in @(
    "ARCH_REVIEW_STAGE1.md", "FFT3D_PLAN.md", "FFT_ENGINE_BLOCK.md",
    "FIT_BUDGET.md", "MEMORY_PROBLEM_BRIEF.md", "PROGRESS_REPORT.md",
    "SOLUTION.md", "WEEK_PLAN.md", "REVIEW_AUG31.md",
    "FFT_Engine_Report.pdf", "Memory_Problem.pdf",
    "fft_chain_flow.mermaid", "fft_engine_flow.mermaid", "fft_engine_simple.mermaid"
)) { Do-Move $f "docs" }
Do-Move "fig" "docs"

# =============================================================================
# 2. ARCHIVE -- stale results that must NOT sit in the root looking official
# =============================================================================
# synth_timing.txt / synth_utilization.txt are from the run that targeted
# xc7a200t (ARTIX), not the KC705 Kintex part -- the wrong-part bug found on
# 31 Aug. Leaving them in the root invites someone to quote them as this
# project's numbers. RESULTS_SYNTH.md reports those same numbers.
# golden_* predate the 4-lane architecture and are not wired to any test.
Write-Host "--- archiving stale results ---" -ForegroundColor Green
foreach ($f in @(
    "synth_timing.txt", "synth_utilization.txt", "RESULTS_SYNTH.md",
    "golden_4lane_out.txt", "golden_cube.npy"
)) { Do-Move $f "attic" }

# =============================================================================
# 3. DELETE -- tool output, regenerated on the next run. No sources here.
# =============================================================================
Write-Host "--- deleting regenerable tool output ---" -ForegroundColor Green

# Vivado / xsim journals and logs, including every rolling backup
Do-DeleteFile "vivado*.jou"
Do-DeleteFile "vivado*.log"
Do-DeleteFile "vivado*.str"
Do-DeleteFile "xsim*.jou"
Do-DeleteFile "xsim*.log"
Do-DeleteFile "xelab.log"
Do-DeleteFile "xelab.pb"
Do-DeleteFile "xvlog.log"
Do-DeleteFile "xvlog.pb"
Do-DeleteFile "dfx_runtime.txt"

# Waveform databases from old runs (~1.3 MB). Regenerated by re-simulating.
Do-DeleteFile "*.wdb"

# Empty file, never written
Do-DeleteFile "generate_hanning.ps1"

# Tool scratch and build output directories. EXACT names only -- see the
# protected list above for why that matters.
Do-DeleteDir ".Xil"                 # Vivado temp
Do-DeleteDir "xsim.dir"             # xsim compiled snapshots
Do-DeleteDir "build"                # smoke-test project, rebuilt by run_pipeline_smoke.tcl
Do-DeleteDir "vivado_proj"          # old project
Do-DeleteDir "vivado_sim"           # old sim project
Do-DeleteDir "sim_scripts"          # exported sim scripts, regenerable
Do-DeleteDir "vivado_engine"        # old Stage-1 engine build
Do-DeleteDir "vivado_engine_kc705"  # rebuilt by scripts/build_engine.tcl

# Zynq-era IP. Superseded by vivado_ip_kc705, which is on the PROTECTED list
# and cannot be removed by this script. Regenerable anyway via
# scripts/create_fft_ip.tcl with BOARD=zybo.
Do-DeleteDir "vivado_ip"

# Emptied by the 2 Sep attic move -- contents already live in attic/.
# ctm_rtl/ only; sim/ and ctm_tb/ still hold real files and are handled in
# step 4 below. Nearly deleted them here -- they LOOKED empty from the
# earlier move, but sim/ holds VERIFICATION.md (rewritten 2 Sep) and
# ctm_tb/ holds tb_ctm.v. Checked before trusting the assumption.
Do-DeleteDir "ctm_rtl"

# =============================================================================
# 4. RELOCATE the last two stragglers, then drop their empty parents
# =============================================================================
Write-Host "--- relocating remaining loose files ---" -ForegroundColor Green
Do-Move "sim\VERIFICATION.md" "docs"     # verification plan -- a doc, not junk
Do-Move "ctm_tb\tb_ctm.v"     "attic"    # CTM testbench predating the 128-bit
                                          # contract; superseded by
                                          # tb/tb_ctm_transpose.sv, kept for history
Do-DeleteDir "sim"
Do-DeleteDir "ctm_tb"

Write-Host ""
if ($Execute) {
    Write-Host "=== done ===" -ForegroundColor Cyan
    Write-Host "Re-run the three checks to confirm nothing needed was removed:" -ForegroundColor Cyan
    Write-Host "  .\scripts\run_unit_tests.ps1"
    Write-Host "  vivado -mode batch -source scripts/run_pipeline_smoke.tcl"
} else {
    Write-Host "=== DRY RUN -- nothing changed ===" -ForegroundColor Cyan
    Write-Host "Read the DELETE lines above. If they look right:" -ForegroundColor Cyan
    Write-Host "  .\scripts\cleanup_repo.ps1 -Execute"
}
Write-Host ""
